[Icon Theme]
Name=BookOS-Tinted-Light
Comment=Base clara para iconos tintados de BookOS
DisplayDepth=32

Inherits=Papirus,breeze,hicolor
Directories=apps/scalable,places/scalable,status/scalable

[apps/scalable]
Size=64
Context=Applications
Type=Scalable
MinSize=16
MaxSize=256

[places/scalable]
Size=64
Context=Places
Type=Scalable
MinSize=16
MaxSize=256

[status/scalable]
Size=24
Context=Status
Type=Scalable
MinSize=16
MaxSize=256
